<#
==============================================================================
 RK Clinic LIS — one-shot Windows setup
==============================================================================
 Run ONCE on the lab machine, as Administrator, AFTER the installer has run.

   powershell -ExecutionPolicy Bypass -File setup-windows.ps1 -ServiceUser labuser

 It does the four things that would otherwise be hand-work, and each of them is
 something that fails quietly when done by hand:

   1. writes the credentials file, generating the two secrets itself so nobody
      reuses a development key or invents a weak one
   2. registers the background service to start at boot, under the right user
      account rather than SYSTEM
   3. opens the firewall for the LIS and the analyzers, on the Private profile
   4. stops the machine sleeping, which would drop serial handles and listeners

 It does NOT install MySQL and does NOT create the schema. MySQL is a separate
 install, and the schema is applied from the developer's machine — deliberately,
 since the migrations are not shipped with the app.

 This script has not been executed on Windows from the build machine, so read it
 before running it and expect to adjust paths if the install location differs.
==============================================================================
#>

[CmdletBinding()]
param(
  # The account the service runs as. Its profile is where the config is written,
  # so this must be the account the lab actually uses.
  [Parameter(Mandatory = $true)]
  [string]$ServiceUser,

  # Needed only if the scheduled task must run while that user is logged off.
  [string]$ServicePassword,

  [string]$InstallDir = 'C:\Program Files\RK Clinic LIS',
  [string]$MysqlHost = 'localhost',
  [int]$MysqlPort = 3306,
  [string]$MysqlUser = 'rk_lis',
  [string]$MysqlDatabase = 'rk_clinic',

  # Prompted for if omitted, so it never has to appear in a command history.
  [string]$MysqlPassword,

  [int]$WebPort = 3000,

  # Restrict web access to the Tailscale range (100.64.0.0/10) instead of opening
  # the port to the whole local network. Use this when the hospital reaches this
  # machine over a VPN rather than from the same LAN — it means a stranger on the
  # lab's wifi cannot open the LIS, while the hospital still can.
  [switch]$TailnetOnly,

  # Skip individual steps when re-running after a partial setup.
  [switch]$SkipFirewall,
  [switch]$SkipTask,
  [switch]$SkipPower
)

$ErrorActionPreference = 'Stop'

function Write-Step { param($m) Write-Host "`n=== $m" -ForegroundColor Cyan }
function Write-Ok   { param($m) Write-Host "  [ok] $m" -ForegroundColor Green }
function Write-Warn { param($m) Write-Host "  [!!] $m" -ForegroundColor Yellow }

# ── Preconditions ───────────────────────────────────────────────────────────

$isAdmin = ([Security.Principal.WindowsPrincipal] `
  [Security.Principal.WindowsIdentity]::GetCurrent()
).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
  throw 'Run this in an Administrator PowerShell. Registering a boot task and firewall rules both require it.'
}

$serviceLauncher = Join-Path $InstallDir 'resources\app\build\service.cmd'
if (-not (Test-Path $serviceLauncher)) {
  throw "Cannot find $serviceLauncher — install the app first, or pass -InstallDir with the real location."
}
Write-Ok "found the app at $InstallDir"

# ── 1. Credentials ──────────────────────────────────────────────────────────
# Written into the SERVICE USER's profile, not the administrator's. This is the
# trap the manual process falls into: an elevated shell has its own APPDATA, so
# a config written with $env:APPDATA lands where the service will never look.

Write-Step 'Credentials'

$userProfile = "C:\Users\$ServiceUser"
if (-not (Test-Path $userProfile)) {
  throw "No profile at $userProfile. The account must have logged in at least once."
}

$dataDir = Join-Path $userProfile 'AppData\Roaming\rk-clinic'
$envFile = Join-Path $dataDir '.env.local'
New-Item -ItemType Directory -Force -Path $dataDir | Out-Null

if (-not $MysqlPassword) {
  $secure = Read-Host "MySQL password for '$MysqlUser'" -AsSecureString
  $MysqlPassword = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
}

# 32 bytes of cryptographic randomness, hex encoded. Generated here so that no
# installation shares a secret with another, or with the development machine.
function New-Secret {
  $bytes = New-Object byte[] 32
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return ($bytes | ForEach-Object { $_.ToString('x2') }) -join ''
}

if (Test-Path $envFile) {
  Write-Warn "$envFile already exists — leaving it alone. Delete it and re-run to regenerate."
} else {
  $content = @"
# RK Clinic LIS — generated by setup-windows.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# Secrets below are unique to this installation. Do not copy them elsewhere.

MYSQL_HOST=$MysqlHost
MYSQL_PORT=$MysqlPort
MYSQL_DATABASE=$MysqlDatabase
MYSQL_USER=$MysqlUser
MYSQL_PASSWORD=$MysqlPassword

JWT_SECRET=$(New-Secret)
LIS_ANALYZER_API_KEY=$(New-Secret)
"@
  Set-Content -Path $envFile -Value $content -Encoding UTF8

  # Readable only by that user and administrators: it holds the database password
  # and the key every analyzer bridge authenticates with.
  $acl = Get-Acl $envFile
  $acl.SetAccessRuleProtection($true, $false)
  $acl.SetAccessRule((New-Object Security.AccessControl.FileSystemAccessRule(
    $ServiceUser, 'FullControl', 'Allow')))
  $acl.SetAccessRule((New-Object Security.AccessControl.FileSystemAccessRule(
    'Administrators', 'FullControl', 'Allow')))
  Set-Acl -Path $envFile -AclObject $acl

  Write-Ok "wrote $envFile with freshly generated secrets"
}

# ── 2. Start at boot ────────────────────────────────────────────────────────

if (-not $SkipTask) {
  Write-Step 'Background service'

  $taskName = 'RK Clinic LIS'
  schtasks /query /tn $taskName *> $null
  if ($LASTEXITCODE -eq 0) {
    Write-Warn 'task already exists — replacing it'
    schtasks /delete /tn $taskName /f *> $null
  }

  $args = @('/create', '/tn', $taskName, '/tr', "`"$serviceLauncher`"",
            '/sc', 'onstart', '/rl', 'highest', '/f', '/ru', $ServiceUser)
  if ($ServicePassword) { $args += @('/rp', $ServicePassword) }

  schtasks @args
  if ($LASTEXITCODE -ne 0) { throw 'schtasks failed to register the service.' }

  Write-Ok "registered '$taskName' to start at boot as $ServiceUser"
  if (-not $ServicePassword) {
    Write-Warn 'no password given, so the task runs only when that user is logged in.'
    Write-Warn 'For an unattended machine, re-run with -ServicePassword.'
  }
}

# ── 3. Firewall ─────────────────────────────────────────────────────────────
# Without these the analyzers cannot dial in and no other machine can open the
# LIS. 3306 is deliberately absent: the database is reached only from this host.

if (-not $SkipFirewall) {
  Write-Step 'Firewall'

  # The analyzer ports are always LAN-local: the instruments sit on a directly
  # cabled segment and dial in from there. Only the web port is reached from the
  # other site, so only it needs widening — and widening it as little as possible.
  $rules = @(
    @{ Name = 'RK LIS Hemat 60';    Port = 8080; Scope = 'private' },
    @{ Name = 'RK LIS Mispa Plus';  Port = 8888; Scope = 'private' }
  )

  foreach ($rule in $rules) {
    netsh advfirewall firewall delete rule name="$($rule.Name)" *> $null
    netsh advfirewall firewall add rule `
      name="$($rule.Name)" dir=in action=allow protocol=TCP `
      localport=$($rule.Port) profile=private *> $null
    Write-Ok "allowed inbound TCP $($rule.Port) from the local network — $($rule.Name)"
  }

  netsh advfirewall firewall delete rule name='RK LIS web' *> $null
  if ($TailnetOnly) {
    # 100.64.0.0/10 is the CGNAT range Tailscale assigns. Any profile, because a
    # VPN adapter is often classified Public and a Private-only rule would not
    # apply to it — but restricted by source address, which is tighter than a
    # profile rule anyway.
    netsh advfirewall firewall add rule `
      name='RK LIS web' dir=in action=allow protocol=TCP `
      localport=$WebPort remoteip=100.64.0.0/10 *> $null
    Write-Ok "allowed inbound TCP $WebPort from the Tailscale range only (100.64.0.0/10)"
  } else {
    netsh advfirewall firewall add rule `
      name='RK LIS web' dir=in action=allow protocol=TCP `
      localport=$WebPort profile=private *> $null
    Write-Ok "allowed inbound TCP $WebPort from the local network"
    Write-Warn 'If the hospital connects over a VPN, re-run with -TailnetOnly for a tighter rule.'
  }

  $public = Get-NetConnectionProfile | Where-Object { $_.NetworkCategory -eq 'Public' }
  if ($public) {
    Write-Warn 'These adapters are classified Public, so the rules above do NOT apply to them:'
    $public | ForEach-Object { Write-Warn "   $($_.InterfaceAlias)" }
    Write-Warn 'If an analyzer is on one of them, set it to Private:'
    Write-Warn '   Set-NetConnectionProfile -InterfaceAlias "<name>" -NetworkCategory Private'
  }
}

# ── 4. Never sleep ──────────────────────────────────────────────────────────
# A sleeping host drops serial handles and TCP listeners exactly like a shutdown,
# and an instrument that transmits into it loses that result for good.

if (-not $SkipPower) {
  Write-Step 'Power'
  powercfg /change standby-timeout-ac 0
  powercfg /change hibernate-timeout-ac 0
  powercfg /change disk-timeout-ac 0
  Write-Ok 'sleep, hibernate and disk timeout disabled on AC power'
}

# ── What is left ────────────────────────────────────────────────────────────

Write-Step 'Still to do, by hand'
Write-Host @"
  0. If the hospital is at another site, install Tailscale on this machine and on
     each machine there, then serve the LIS over it with TLS:
       tailscale serve --bg https / http://127.0.0.1:$WebPort
     Staff then open https://<this-machine>.<tailnet>.ts.net with a real
     certificate, instead of sending passwords over plain HTTP.

  1. MySQL 8.4 LTS must be installed and running, with a database named
     '$MysqlDatabase' and the user '$MysqlUser' able to reach it.

  2. Apply the schema from the developer machine:
       npm run db:migrate
       npm run db:seed
     then set bind-address=127.0.0.1 in my.ini and restart MySQL.

  3. Give the analyzer-side network adapter the address 192.168.1.3, so the
     instruments need no reconfiguring.

  4. Schedule a mysqldump to somewhere off this machine. Every patient record
     lives here and nowhere else.

  Then reboot, and check:
    - http://127.0.0.1:$WebPort/api/health  returns 200
    - the tray icon shows the analyzer tiles live
    - another PC on the LAN can open http://<this-machine-ip>:$WebPort
"@ -ForegroundColor Gray

Write-Host "`nSetup complete.`n" -ForegroundColor Green
